version: "2"
services:
  api:
    build: .
    volumes:
        - "./:/app"
        - "/app/node_modules"
    ports:
        - "8000:8000"
    networks:
        - nodeapp-network
    depends_on:
        - "db"
    links:
      - db


  db:
    image: mongo:latest
    container_name: "mongodb"
    environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
    volumes:
        - data-volume:/data/db
    networks:
        - nodeapp-network
    ports:
        - 27017:27017
    command: mongod

volumes:
  data-volume:
    
networks:
  nodeapp-network:
    driver: bridge